<?php $_config_vars = array (
  'language' => 'en',
  'charset' => 'utf-8',
  'locale' => 
  array (
    0 => 'en',
    1 => 'en_EN@euro',
    2 => 'eng',
  ),
  'dir' => 'ltr',
  'time_format' => '%Y-%m-%d, %H:%M',
  'time_format_full' => '%A, %B %d, %Y, %H:%M',
  'date_format' => '%d.%m.%Y',
  'rss_time_format' => '%a, %d %b %Y %H:%M:%S +0000',
  'unknown_user' => 'unknown',
  'db_error' => 'Database error!',
  'mail_error' => 'Mail server not available - please try again later!',
  'contact_hl' => 'E-mail to the forum administrator',
  'contact_user_hl' => 'E-mail to [recipient_name]',
  'impossible_to_contact' => 'This user cannot be contacted!',
  'contact_doesnt_exist' => 'This contact doesn\'t exist!',
  'sender_address_caption' => 'Sender e-mail:',
  'subject_caption' => 'Subject:',
  'message_caption' => 'Message:',
  'message_submit_caption' => 'OK - Send message',
  'email_sent' => 'The message has been sent successfully.',
  'error_no_text' => 'No message enetered',
  'error_no_email' => 'No sender e-mail address specified',
  'error_no_subject' => 'No subject entered',
  'error_email_invalid' => 'The e-mail address is invalid',
  'error_not_accepted_word' => 'The mail contains at least one not accepted word',
  'error_email_subject_too_long' => 'The subject is too long',
  'error_email_text_too_long' => 'The message is too long ([text_length] characters - only [text_maxlength] characters are allowed)',
  'error_spam_suspicion' => 'Spam suspicion! Please modify your message (e.g. remove Links)',
  'error_mailserver' => 'Failed to send the mail!',
); ?>