<?php $_config_vars = array (
  'language' => 'en',
  'charset' => 'utf-8',
  'locale' => 
  array (
    0 => 'en',
    1 => 'en_EN@euro',
    2 => 'eng',
  ),
  'dir' => 'ltr',
  'time_format' => '%Y-%m-%d, %H:%M',
  'time_format_full' => '%A, %B %d, %Y, %H:%M',
  'date_format' => '%d.%m.%Y',
  'rss_time_format' => '%a, %d %b %Y %H:%M:%S +0000',
  'unknown_user' => 'unknown',
  'db_error' => 'Database error!',
  'mail_error' => 'Mail server not available - please try again later!',
  'user_name' => 'Username',
  'user_type' => 'Type',
  'admin' => 'Admin',
  'mod' => 'Moderator',
  'user' => 'User',
  'user_email' => 'E-mail',
  'user_hp' => 'Homepage',
  'mailto_user' => 'E-mail to [user]',
  'email' => 'E-mail',
  'homepage' => 'Homepage',
  'user_postings' => 'Postings',
  'user_online' => 'Online',
  'user_blockage' => 'Lock',
  'online' => 'online',
  'locked' => 'locked',
  'lock_title' => 'lock user',
  'unlocked' => 'off',
); ?>